### ISSUE TITLE
Crash on log4j 2.7

### ISSUE THREAD

**Issue by gnuhel** [loune/log4j2-android#1]
Hi @loune 

where trying to use log4j 2.7 the app crash. Could you tell me why?

Thanks in advance

**Comment by loune** [comment]
Hi @gnuhel - this is most likely because log4net 2.4+ require some Java 7 APIs (as [mentioned in my blog post](https://loune.net/2016/05/using-log4j2-2-3-with-android/)) That's why I created this example in log4net 2.3

**Comment by gnuhel** [comment]
Thanks for your reply, I had an issue where it could not create a new log for RollingAppender `Unable to rename file ...`

https://issues.apache.org/jira/browse/LOG4J2-1173

That's why I wanted to try it with the newest version.
